import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#f4fafb",
        "surface-variant": "#e0e7e7",
        "inverse-primary": "#a0e0de",
        "surface-tint": "#0d7377",
        secondary: "#4a7c7a",
        "on-error-container": "#93000a",
        "on-background": "#1a1c1c",
        "on-tertiary-container": "#3a4500",
        "on-secondary-fixed": "#0a1f1e",
        outline: "#6d7a79",
        "tertiary-fixed-dim": "#c9d045",
        "on-primary-fixed": "#002020",
        "error-container": "#ffdad6",
        "surface-container-high": "#e6ecec",
        "on-primary-container": "#f0fffe",
        "primary-container": "#4fb5b5",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#b0d5d3",
        "on-secondary": "#ffffff",
        "secondary-container": "#cdedeb",
        "on-secondary-container": "#326260",
        tertiary: "#6a7200",
        primary: "#0d7377",
        "on-surface": "#1a1c1c",
        "on-secondary-fixed-variant": "#1b4a48",
        "surface-dim": "#d9dfde",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#005b5e",
        "tertiary-container": "#b5bd34",
        "on-tertiary-fixed-variant": "#3f4700",
        "on-error": "#ffffff",
        "inverse-surface": "#2f3131",
        surface: "#f4fafb",
        "surface-bright": "#f4fafb",
        "tertiary-fixed": "#e7f060",
        "outline-variant": "#c2c9c8",
        "on-surface-variant": "#404948",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e0e6e6",
        "secondary-fixed": "#cdedeb",
        "primary-fixed-dim": "#a0e0de",
        "inverse-on-surface": "#eff5f4",
        "on-tertiary-fixed": "#202600",
        "surface-container-low": "#f0f6f5",
        "primary-fixed": "#c5f5f3",
        error: "#ba1a1a",
        "surface-container": "#eaf0ef",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
        "4xl": "2rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "20px",
        gutter: "24px",
        "margin-desktop": "40px",
        "container-max": "1200px",
        "section-padding": "96px",
        "card-padding": "40px",
      },
      fontFamily: {
        display: ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-bold": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-bold": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
      keyframes: {
        ripple: {
          "0%, 100%": { transform: "scale(1)", opacity: "1" },
          "50%": { transform: "scale(1.5)", opacity: "0.5" },
        },
        orbit: {
          "0%": { transform: "rotate(0deg) translateX(var(--radius)) rotate(0deg)" },
          "100%": { transform: "rotate(360deg) translateX(var(--radius)) rotate(-360deg)" },
        },
      },
      animation: {
        ripple: "ripple 3s ease-out infinite",
        orbit: "orbit calc(var(--duration) * 1s) linear infinite",
      },
    },
  },
};

export default config;
